### PR TITLE
Make venv to not use symlink but rather copy the binaries

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes https://github.com/yyuu/pyenv/issues/770 which in fact should have been opened in pyenv-virtualenv repo, not pyenv

### CODE REVIEW

**Comment by DanyC97** [comment]
is anyone looking after this repo? if so happy to push/ change the test to make the CI build happy

**Comment by yyuu** [comment]
Please fix CI

**Comment by blueyed** [comment]
@yyuu 
Do you agree with the change (explained in https://github.com/yyuu/pyenv/issues/770#issuecomment-274292478)?
I do not understand it really, and it might be a bad hack, that causes more data usage after all!?

**Comment by yyuu** [comment]
About data usage, the increasing is just about the size of python executables. I think increasing of data usage of few ten MB must not be a problem on current systems.

Honestly speaking, I'm still not sure what is causing the problem. I suspect there's some problem when creating virtual environment with venv.

**Comment by DanyC97** [comment]
@yyuu  @blueyed the issue it boils down to how `venv` behaves by default:

*default*
`python -m venv /usr/local/opt/pyenv/versions/3.6.0/envs/pyenv-test2` it creates a symlink

*using --copies*
`python -m venv --copies /usr/local/opt/pyenv/versions/3.6.0/envs/pyenv-test2` it copies the python binary

as for the data usage the python binary is 2.8 M (imo is acceptable). Note for python 2.7 the binary is 1.9 hence not a big issue

I'll fix the CI soon

**Comment by iraquitan** [comment]
Any updates about this PR? Will it be merged?

**Comment by DanyC97** [comment]
@iraquitan i doubt it will, been open for such a long time (sorry, is out of my control)

**Comment by lwilke** [comment]
Is the pyenv-virtualenv plugin unmaintained? @yyuu
There are now several tickets open regarding the changed venv behaviour introduced in python3.
At least two different PRs are open which would fix this.
I would be willing to help if help is wanted.

**Comment by 1oglop1** [comment]
@lwilke It looks like that @yyuu is the only one with merge rights but is pretty busy.
Imo it would be wise to delegate this to more people, for example @blueyed would be great candidate imo.

**Comment by yyuu** [comment]
The reason why this isn't merged is clear; this PR is outdated and is conflicted with current master branch. Plus, is also breaking tests of the plugin.

This repo has multiple number of maintainers, but we cannot implement all feature requests since we are not paid coders, and to me I don't have any issue with current behaviour since I am not using PyCharm at all. If someone interested in _fixing_ the problem, please open another PR to address the conflicts and test breakages.

**Comment by chrahunt** [comment]
I'm -1 on this for two reasons:

1. The motivation for this change was a bug in PyCharm 2016.3 which was subsequently fixed in 2017.1 per [this comment](https://youtrack.jetbrains.com/issue/PY-21787#focus=streamItem-27-2915242.0-0).
2. As mentioned in pyenv/pyenv#1190 - convenient usage of python-gdb.py only works when the virtualenv is installed using symlinks - so this change would make the combination of pyenv-virtualenv and python-gdb.py being installed by pyenv useless.

**Comment by DanyC97** [comment]
closing based on feedback received from @yyuu  and @chrahunt

**Pull request closed without merging**
